package ef.droolsFusion

//list any import classes here.
import zhwb.droolsFusion.Workorder;


//declare any global variables here
declare Workorder
	@role(event)
end



rule "Surrey money"

    when
        //conditions
        Number( $totalSalesAmount : intValue, intValue > 1000)
        from accumulate (Workorder ($hours : hours, $costPerHour : costPerHour)
        from entry-point Surrey,
        sum($hours*$costPerHour))
    then
        //actions
		System.out.println("Surrey - has passed its amount of money allowed, money is :"+$totalSalesAmount);
end
